version: '3.7'


services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
            - SECRET_KEY=4l7)%mapzx=c27-fk86ho%$$2f001#d_go)ka-s5u^^$vaxo1m&
            - DEBUG=True
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
           
